package com.techno.studentguide.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY.
 */
public class Category {

    private Long id;
    private String category_id;
    private String parent_category_id;
    private String name;
    private String count;
    private String category_name_en;
    private String category_name_ar;
    private Boolean filter_by;
    private String category_created_datetime;
    private String category_updated_datetime;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String category_id, String parent_category_id, String name, String count, String category_name_en, String category_name_ar, Boolean filter_by, String category_created_datetime, String category_updated_datetime) {
        this.id = id;
        this.category_id = category_id;
        this.parent_category_id = parent_category_id;
        this.name = name;
        this.count = count;
        this.category_name_en = category_name_en;
        this.category_name_ar = category_name_ar;
        this.filter_by = filter_by;
        this.category_created_datetime = category_created_datetime;
        this.category_updated_datetime = category_updated_datetime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategory_id() {
        return category_id;
    }

    public void setCategory_id(String category_id) {
        this.category_id = category_id;
    }

    public String getParent_category_id() {
        return parent_category_id;
    }

    public void setParent_category_id(String parent_category_id) {
        this.parent_category_id = parent_category_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getCategory_name_en() {
        return category_name_en;
    }

    public void setCategory_name_en(String category_name_en) {
        this.category_name_en = category_name_en;
    }

    public String getCategory_name_ar() {
        return category_name_ar;
    }

    public void setCategory_name_ar(String category_name_ar) {
        this.category_name_ar = category_name_ar;
    }

    public Boolean getFilter_by() {
        return filter_by;
    }

    public void setFilter_by(Boolean filter_by) {
        this.filter_by = filter_by;
    }

    public String getCategory_created_datetime() {
        return category_created_datetime;
    }

    public void setCategory_created_datetime(String category_created_datetime) {
        this.category_created_datetime = category_created_datetime;
    }

    public String getCategory_updated_datetime() {
        return category_updated_datetime;
    }

    public void setCategory_updated_datetime(String category_updated_datetime) {
        this.category_updated_datetime = category_updated_datetime;
    }

}
