package com.techno.studentguide.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1,005): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1005;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CategoryDao.createTable(db, ifNotExists);
        VendorDao.createTable(db, ifNotExists);
        VendorAreaListDao.createTable(db, ifNotExists);
        VendorCategoryLinkDao.createTable(db, ifNotExists);
        VendorAreaLinkDao.createTable(db, ifNotExists);
        VendorViewDao.createTable(db, ifNotExists);
        VendorPhotoDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CategoryDao.dropTable(db, ifExists);
        VendorDao.dropTable(db, ifExists);
        VendorAreaListDao.dropTable(db, ifExists);
        VendorCategoryLinkDao.dropTable(db, ifExists);
        VendorAreaLinkDao.dropTable(db, ifExists);
        VendorViewDao.dropTable(db, ifExists);
        VendorPhotoDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CategoryDao.class);
        registerDaoClass(VendorDao.class);
        registerDaoClass(VendorAreaListDao.class);
        registerDaoClass(VendorCategoryLinkDao.class);
        registerDaoClass(VendorAreaLinkDao.class);
        registerDaoClass(VendorViewDao.class);
        registerDaoClass(VendorPhotoDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
