package com.techno.studentguide.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig vendorDaoConfig;
    private final DaoConfig vendorAreaListDaoConfig;
    private final DaoConfig vendorCategoryLinkDaoConfig;
    private final DaoConfig vendorAreaLinkDaoConfig;
    private final DaoConfig vendorViewDaoConfig;
    private final DaoConfig vendorPhotoDaoConfig;

    private final CategoryDao categoryDao;
    private final VendorDao vendorDao;
    private final VendorAreaListDao vendorAreaListDao;
    private final VendorCategoryLinkDao vendorCategoryLinkDao;
    private final VendorAreaLinkDao vendorAreaLinkDao;
    private final VendorViewDao vendorViewDao;
    private final VendorPhotoDao vendorPhotoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        vendorDaoConfig = daoConfigMap.get(VendorDao.class).clone();
        vendorDaoConfig.initIdentityScope(type);

        vendorAreaListDaoConfig = daoConfigMap.get(VendorAreaListDao.class).clone();
        vendorAreaListDaoConfig.initIdentityScope(type);

        vendorCategoryLinkDaoConfig = daoConfigMap.get(VendorCategoryLinkDao.class).clone();
        vendorCategoryLinkDaoConfig.initIdentityScope(type);

        vendorAreaLinkDaoConfig = daoConfigMap.get(VendorAreaLinkDao.class).clone();
        vendorAreaLinkDaoConfig.initIdentityScope(type);

        vendorViewDaoConfig = daoConfigMap.get(VendorViewDao.class).clone();
        vendorViewDaoConfig.initIdentityScope(type);

        vendorPhotoDaoConfig = daoConfigMap.get(VendorPhotoDao.class).clone();
        vendorPhotoDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        vendorDao = new VendorDao(vendorDaoConfig, this);
        vendorAreaListDao = new VendorAreaListDao(vendorAreaListDaoConfig, this);
        vendorCategoryLinkDao = new VendorCategoryLinkDao(vendorCategoryLinkDaoConfig, this);
        vendorAreaLinkDao = new VendorAreaLinkDao(vendorAreaLinkDaoConfig, this);
        vendorViewDao = new VendorViewDao(vendorViewDaoConfig, this);
        vendorPhotoDao = new VendorPhotoDao(vendorPhotoDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Vendor.class, vendorDao);
        registerDao(VendorAreaList.class, vendorAreaListDao);
        registerDao(VendorCategoryLink.class, vendorCategoryLinkDao);
        registerDao(VendorAreaLink.class, vendorAreaLinkDao);
        registerDao(VendorView.class, vendorViewDao);
        registerDao(VendorPhoto.class, vendorPhotoDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        vendorDaoConfig.getIdentityScope().clear();
        vendorAreaListDaoConfig.getIdentityScope().clear();
        vendorCategoryLinkDaoConfig.getIdentityScope().clear();
        vendorAreaLinkDaoConfig.getIdentityScope().clear();
        vendorViewDaoConfig.getIdentityScope().clear();
        vendorPhotoDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public VendorDao getVendorDao() {
        return vendorDao;
    }

    public VendorAreaListDao getVendorAreaListDao() {
        return vendorAreaListDao;
    }

    public VendorCategoryLinkDao getVendorCategoryLinkDao() {
        return vendorCategoryLinkDao;
    }

    public VendorAreaLinkDao getVendorAreaLinkDao() {
        return vendorAreaLinkDao;
    }

    public VendorViewDao getVendorViewDao() {
        return vendorViewDao;
    }

    public VendorPhotoDao getVendorPhotoDao() {
        return vendorPhotoDao;
    }

}
