package com.techno.studentguide.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table VENDOR_PHOTO.
*/
public class VendorPhotoDao extends AbstractDao<VendorPhoto, Long> {

    public static final String TABLENAME = "VENDOR_PHOTO";

    /**
     * Properties of entity VendorPhoto.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Photo_id = new Property(1, String.class, "photo_id", false, "PHOTO_ID");
        public final static Property Vendor_id = new Property(2, String.class, "vendor_id", false, "VENDOR_ID");
        public final static Property Photo_url = new Property(3, String.class, "photo_url", false, "PHOTO_URL");
        public final static Property Photo_added_datetime = new Property(4, String.class, "photo_added_datetime", false, "PHOTO_ADDED_DATETIME");
    };


    public VendorPhotoDao(DaoConfig config) {
        super(config);
    }
    
    public VendorPhotoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'VENDOR_PHOTO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PHOTO_ID' TEXT," + // 1: photo_id
                "'VENDOR_ID' TEXT," + // 2: vendor_id
                "'PHOTO_URL' TEXT," + // 3: photo_url
                "'PHOTO_ADDED_DATETIME' TEXT);"); // 4: photo_added_datetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VENDOR_PHOTO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, VendorPhoto entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String photo_id = entity.getPhoto_id();
        if (photo_id != null) {
            stmt.bindString(2, photo_id);
        }
 
        String vendor_id = entity.getVendor_id();
        if (vendor_id != null) {
            stmt.bindString(3, vendor_id);
        }
 
        String photo_url = entity.getPhoto_url();
        if (photo_url != null) {
            stmt.bindString(4, photo_url);
        }
 
        String photo_added_datetime = entity.getPhoto_added_datetime();
        if (photo_added_datetime != null) {
            stmt.bindString(5, photo_added_datetime);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public VendorPhoto readEntity(Cursor cursor, int offset) {
        VendorPhoto entity = new VendorPhoto( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // photo_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // vendor_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // photo_url
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // photo_added_datetime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, VendorPhoto entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPhoto_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVendor_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPhoto_url(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPhoto_added_datetime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(VendorPhoto entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(VendorPhoto entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
