package com.techno.studentguide.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table VENDOR_CATEGORY_LINK.
*/
public class VendorCategoryLinkDao extends AbstractDao<VendorCategoryLink, Long> {

    public static final String TABLENAME = "VENDOR_CATEGORY_LINK";

    /**
     * Properties of entity VendorCategoryLink.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Link_id = new Property(1, String.class, "link_id", false, "LINK_ID");
        public final static Property Vendor_id = new Property(2, String.class, "vendor_id", false, "VENDOR_ID");
        public final static Property Category_id = new Property(3, String.class, "category_id", false, "CATEGORY_ID");
    };


    public VendorCategoryLinkDao(DaoConfig config) {
        super(config);
    }
    
    public VendorCategoryLinkDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'VENDOR_CATEGORY_LINK' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'LINK_ID' TEXT," + // 1: link_id
                "'VENDOR_ID' TEXT," + // 2: vendor_id
                "'CATEGORY_ID' TEXT);"); // 3: category_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VENDOR_CATEGORY_LINK'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, VendorCategoryLink entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String link_id = entity.getLink_id();
        if (link_id != null) {
            stmt.bindString(2, link_id);
        }
 
        String vendor_id = entity.getVendor_id();
        if (vendor_id != null) {
            stmt.bindString(3, vendor_id);
        }
 
        String category_id = entity.getCategory_id();
        if (category_id != null) {
            stmt.bindString(4, category_id);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public VendorCategoryLink readEntity(Cursor cursor, int offset) {
        VendorCategoryLink entity = new VendorCategoryLink( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // link_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // vendor_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // category_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, VendorCategoryLink entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLink_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVendor_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCategory_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(VendorCategoryLink entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(VendorCategoryLink entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
