package com.techno.studentguide.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VENDOR_AREA_LIST.
 */
public class VendorAreaList {

    private Long id;
    private String area_id;
    private String area_name_en;
    private String area_name_ar;
    static boolean selected = false;
    public VendorAreaList() {
    }

    public VendorAreaList(Long id) {
        this.id = id;
    }

    public VendorAreaList(Long id, String area_id, String area_name_en, String area_name_ar) {
        this.id = id;
        this.area_id = area_id;
        this.area_name_en = area_name_en;
        this.area_name_ar = area_name_ar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getArea_id() {
        return area_id;
    }

    public void setArea_id(String area_id) {
        this.area_id = area_id;
    }

    public String getArea_name_en() {
        return area_name_en;
    }

    public void setArea_name_en(String area_name_en) {
        this.area_name_en = area_name_en;
    }

    public String getArea_name_ar() {
        return area_name_ar;
    }

    public void setArea_name_ar(String area_name_ar) {
        this.area_name_ar = area_name_ar;
    }

    public static boolean isSelected() {
        return selected;
    }

    public static void setSelected(boolean selected) {
        VendorAreaList.selected = selected;
    }
}
