package com.techno.studentguide.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table VENDOR_VIEW.
*/
public class VendorViewDao extends AbstractDao<VendorView, Long> {

    public static final String TABLENAME = "VENDOR_VIEW";

    /**
     * Properties of entity VendorView.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property View_id = new Property(1, String.class, "view_id", false, "VIEW_ID");
        public final static Property Vendor_id = new Property(2, String.class, "vendor_id", false, "VENDOR_ID");
        public final static Property View_date = new Property(3, String.class, "view_date", false, "VIEW_DATE");
        public final static Property View_number_of_views = new Property(4, String.class, "view_number_of_views", false, "VIEW_NUMBER_OF_VIEWS");
    };


    public VendorViewDao(DaoConfig config) {
        super(config);
    }
    
    public VendorViewDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'VENDOR_VIEW' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'VIEW_ID' TEXT," + // 1: view_id
                "'VENDOR_ID' TEXT," + // 2: vendor_id
                "'VIEW_DATE' TEXT," + // 3: view_date
                "'VIEW_NUMBER_OF_VIEWS' TEXT);"); // 4: view_number_of_views
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VENDOR_VIEW'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, VendorView entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String view_id = entity.getView_id();
        if (view_id != null) {
            stmt.bindString(2, view_id);
        }
 
        String vendor_id = entity.getVendor_id();
        if (vendor_id != null) {
            stmt.bindString(3, vendor_id);
        }
 
        String view_date = entity.getView_date();
        if (view_date != null) {
            stmt.bindString(4, view_date);
        }
 
        String view_number_of_views = entity.getView_number_of_views();
        if (view_number_of_views != null) {
            stmt.bindString(5, view_number_of_views);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public VendorView readEntity(Cursor cursor, int offset) {
        VendorView entity = new VendorView( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // view_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // vendor_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // view_date
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // view_number_of_views
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, VendorView entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setView_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVendor_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setView_date(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setView_number_of_views(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(VendorView entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(VendorView entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
