package com.techno.studentguide.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VENDOR_CATEGORY_LINK.
 */
public class VendorCategoryLink {

    private Long id;
    private String link_id;
    private String vendor_id;
    private String category_id;

    public VendorCategoryLink() {
    }

    public VendorCategoryLink(Long id) {
        this.id = id;
    }

    public VendorCategoryLink(Long id, String link_id, String vendor_id, String category_id) {
        this.id = id;
        this.link_id = link_id;
        this.vendor_id = vendor_id;
        this.category_id = category_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLink_id() {
        return link_id;
    }

    public void setLink_id(String link_id) {
        this.link_id = link_id;
    }

    public String getVendor_id() {
        return vendor_id;
    }

    public void setVendor_id(String vendor_id) {
        this.vendor_id = vendor_id;
    }

    public String getCategory_id() {
        return category_id;
    }

    public void setCategory_id(String category_id) {
        this.category_id = category_id;
    }

}
