package com.techno.studentguide.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VENDOR_VIEW.
 */
public class VendorView {

    private Long id;
    private String view_id;
    private String vendor_id;
    private String view_date;
    private String view_number_of_views;

    public VendorView() {
    }

    public VendorView(Long id) {
        this.id = id;
    }

    public VendorView(Long id, String view_id, String vendor_id, String view_date, String view_number_of_views) {
        this.id = id;
        this.view_id = view_id;
        this.vendor_id = vendor_id;
        this.view_date = view_date;
        this.view_number_of_views = view_number_of_views;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getView_id() {
        return view_id;
    }

    public void setView_id(String view_id) {
        this.view_id = view_id;
    }

    public String getVendor_id() {
        return vendor_id;
    }

    public void setVendor_id(String vendor_id) {
        this.vendor_id = vendor_id;
    }

    public String getView_date() {
        return view_date;
    }

    public void setView_date(String view_date) {
        this.view_date = view_date;
    }

    public String getView_number_of_views() {
        return view_number_of_views;
    }

    public void setView_number_of_views(String view_number_of_views) {
        this.view_number_of_views = view_number_of_views;
    }

}
