package com.techno.studentguide.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VENDOR_PHOTO.
 */
public class VendorPhoto {

    private Long id;
    private String photo_id;
    private String vendor_id;
    private String photo_url;
    private String photo_added_datetime;

    public VendorPhoto() {
    }

    public VendorPhoto(Long id) {
        this.id = id;
    }

    public VendorPhoto(Long id, String photo_id, String vendor_id, String photo_url, String photo_added_datetime) {
        this.id = id;
        this.photo_id = photo_id;
        this.vendor_id = vendor_id;
        this.photo_url = photo_url;
        this.photo_added_datetime = photo_added_datetime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhoto_id() {
        return photo_id;
    }

    public void setPhoto_id(String photo_id) {
        this.photo_id = photo_id;
    }

    public String getVendor_id() {
        return vendor_id;
    }

    public void setVendor_id(String vendor_id) {
        this.vendor_id = vendor_id;
    }

    public String getPhoto_url() {
        return photo_url;
    }

    public void setPhoto_url(String photo_url) {
        this.photo_url = photo_url;
    }

    public String getPhoto_added_datetime() {
        return photo_added_datetime;
    }

    public void setPhoto_added_datetime(String photo_added_datetime) {
        this.photo_added_datetime = photo_added_datetime;
    }

}
