package com.techno.studentguide.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VENDOR_AREA_LINK.
 */
public class VendorAreaLink {

    private Long id;
    private String link_id;
    private String vendor_id;
    private String area_id;

    public VendorAreaLink() {
    }

    public VendorAreaLink(Long id) {
        this.id = id;
    }

    public VendorAreaLink(Long id, String link_id, String vendor_id, String area_id) {
        this.id = id;
        this.link_id = link_id;
        this.vendor_id = vendor_id;
        this.area_id = area_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLink_id() {
        return link_id;
    }

    public void setLink_id(String link_id) {
        this.link_id = link_id;
    }

    public String getVendor_id() {
        return vendor_id;
    }

    public void setVendor_id(String vendor_id) {
        this.vendor_id = vendor_id;
    }

    public String getArea_id() {
        return area_id;
    }

    public void setArea_id(String area_id) {
        this.area_id = area_id;
    }

}
