package com.techno.studentguide.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VENDOR.
 */
public class Vendor {

    private Long id;
    private String vendor_id;
    private String vendor_logo;
    private String vendor_name_en;
    private String vendor_name_ar;
    private String vendor_description_en;
    private String vendor_description_ar;
    private String vendor_phone1;
    private String vendor_phone2;
    private String vendor_youtube_video;
    private String vendor_social_instagram;
    private String vendor_social_twitter;
    private String vendor_location;
    private String vendor_address_text_en;
    private String vendor_address_text_ar;
    private String vendor_account_start_date;
    private String vendor_account_end_date;
    private String sort_order;

    public Vendor() {
    }

    public Vendor(Long id) {
        this.id = id;
    }

    public Vendor(Long id, String vendor_id, String vendor_logo, String vendor_name_en, String vendor_name_ar, String vendor_description_en, String vendor_description_ar, String vendor_phone1, String vendor_phone2, String vendor_youtube_video, String vendor_social_instagram, String vendor_social_twitter, String vendor_location, String vendor_address_text_en, String vendor_address_text_ar, String vendor_account_start_date, String vendor_account_end_date, String sort_order) {
        this.id = id;
        this.vendor_id = vendor_id;
        this.vendor_logo = vendor_logo;
        this.vendor_name_en = vendor_name_en;
        this.vendor_name_ar = vendor_name_ar;
        this.vendor_description_en = vendor_description_en;
        this.vendor_description_ar = vendor_description_ar;
        this.vendor_phone1 = vendor_phone1;
        this.vendor_phone2 = vendor_phone2;
        this.vendor_youtube_video = vendor_youtube_video;
        this.vendor_social_instagram = vendor_social_instagram;
        this.vendor_social_twitter = vendor_social_twitter;
        this.vendor_location = vendor_location;
        this.vendor_address_text_en = vendor_address_text_en;
        this.vendor_address_text_ar = vendor_address_text_ar;
        this.vendor_account_start_date = vendor_account_start_date;
        this.vendor_account_end_date = vendor_account_end_date;
        this.sort_order = sort_order;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVendor_id() {
        return vendor_id;
    }

    public void setVendor_id(String vendor_id) {
        this.vendor_id = vendor_id;
    }

    public String getVendor_logo() {
        return vendor_logo;
    }

    public void setVendor_logo(String vendor_logo) {
        this.vendor_logo = vendor_logo;
    }

    public String getVendor_name_en() {
        return vendor_name_en;
    }

    public void setVendor_name_en(String vendor_name_en) {
        this.vendor_name_en = vendor_name_en;
    }

    public String getVendor_name_ar() {
        return vendor_name_ar;
    }

    public void setVendor_name_ar(String vendor_name_ar) {
        this.vendor_name_ar = vendor_name_ar;
    }

    public String getVendor_description_en() {
        return vendor_description_en;
    }

    public void setVendor_description_en(String vendor_description_en) {
        this.vendor_description_en = vendor_description_en;
    }

    public String getVendor_description_ar() {
        return vendor_description_ar;
    }

    public void setVendor_description_ar(String vendor_description_ar) {
        this.vendor_description_ar = vendor_description_ar;
    }

    public String getVendor_phone1() {
        return vendor_phone1;
    }

    public void setVendor_phone1(String vendor_phone1) {
        this.vendor_phone1 = vendor_phone1;
    }

    public String getVendor_phone2() {
        return vendor_phone2;
    }

    public void setVendor_phone2(String vendor_phone2) {
        this.vendor_phone2 = vendor_phone2;
    }

    public String getVendor_youtube_video() {
        return vendor_youtube_video;
    }

    public void setVendor_youtube_video(String vendor_youtube_video) {
        this.vendor_youtube_video = vendor_youtube_video;
    }

    public String getVendor_social_instagram() {
        return vendor_social_instagram;
    }

    public void setVendor_social_instagram(String vendor_social_instagram) {
        this.vendor_social_instagram = vendor_social_instagram;
    }

    public String getVendor_social_twitter() {
        return vendor_social_twitter;
    }

    public void setVendor_social_twitter(String vendor_social_twitter) {
        this.vendor_social_twitter = vendor_social_twitter;
    }

    public String getVendor_location() {
        return vendor_location;
    }

    public void setVendor_location(String vendor_location) {
        this.vendor_location = vendor_location;
    }

    public String getVendor_address_text_en() {
        return vendor_address_text_en;
    }

    public void setVendor_address_text_en(String vendor_address_text_en) {
        this.vendor_address_text_en = vendor_address_text_en;
    }

    public String getVendor_address_text_ar() {
        return vendor_address_text_ar;
    }

    public void setVendor_address_text_ar(String vendor_address_text_ar) {
        this.vendor_address_text_ar = vendor_address_text_ar;
    }

    public String getVendor_account_start_date() {
        return vendor_account_start_date;
    }

    public void setVendor_account_start_date(String vendor_account_start_date) {
        this.vendor_account_start_date = vendor_account_start_date;
    }

    public String getVendor_account_end_date() {
        return vendor_account_end_date;
    }

    public void setVendor_account_end_date(String vendor_account_end_date) {
        this.vendor_account_end_date = vendor_account_end_date;
    }

    public String getSort_order() {
        return sort_order;
    }

    public void setSort_order(String sort_order) {
        this.sort_order = sort_order;
    }

}
